name: Deploy Serverless

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  LAMBDA_NAME: event-trigger-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::174405733611:role/github-oidc-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      # ---------- LAMBDA DEPLOY ----------
      - name: Package Lambda
        run: |
          cd aws_workflow
          zip -r ../function.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_NAME \
            --zip-file fileb://function.zip
